CO_SA:
  drivername: postgresql
  dbname: OLTPNEW
  user: postgres
  password: postgres
  host: localhost
  port: 5432

ETL_PRO:
  drivername: postgresql
  dbname: prueba
  user: postgres
  password: postgres
  host: localhost
  port: 5432

LOAD_DIMENSIONS:
  True
