CO_SA:
  drivername: postgresql
  dbname: OLTPNEW
  user: postgres
  password: postgres
  host: localhost
  port: 5432

ETL_PRO:
  drivername: postgresql
  dbname: prueba
  user: postgres
  password: postgres
  host: localhost
  port: 5432

SQL_SERVER_DW:
  drivername: mssql+pyodbc
  dbname: AdventureWorksDW2022
  user: sa
  password: r00t.R00T
  host: localhost
  port: 1433
  driver: FreeTDS

LOAD_DIMENSIONS:
  True
