CO_SA:
  drivername: postgresql
  dbname: OLTPNEW
  user: Miguel
  password: miguel
  host: localhost
  port: 5432

ETL_PRO:
  drivername: postgresql
  dbname: prueba
  user: Miguel
  password: miguel
  host: localhost
  port: 5432

LOAD_DIMENSIONS:
  True
